# site settings
title: CJ's Portfolio
subtitle:
email: cj@pulmano.com
description: CJ's website for random things.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: CJ Pulmano
street_address:
city:
state:
zip_code:
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cjpulmano
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/cjpulmano/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
